user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    upstream genial {
        server 127.0.0.1:5000;
    }

    server {
        listen 80;
        server_name geniteste.in;

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name geniteste.in;
        client_max_body_size 2G;
        ssl_certificate /etc/letsencrypt/live/geniteste.in/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/geniteste.in/privkey.pem;
        # ssl_certificate /etc/nginx/certs/fullchain.pem;
        # ssl_certificate_key /etc/nginx/certs/privkey.pem;

        location / {
            root /home/renato/src/genial-api/.local/spa/;
            index index.html;
            try_files $uri $uri/ /index.html;
        }


        location /api {
            proxy_pass http://genial;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /admin {
            proxy_pass http://genial;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /proposta {
            proxy_pass http://genial;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /static/ {
            alias /home/genial/src/genial-api/flask_app/static/;
        }
    }
}

